include $(srctree)/drivers/misc/mediatek/Makefile.custom

ccflags-y += -I$(srctree)/arch/arm/mach-$(MTK_PLATFORM)/$(ARCH_MTK_PROJECT)/touchpanel/MXT144U/
ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/MXT144U/
ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/

obj-y	+=  atmel_mxt.o
