#ifndef __CUST_CWMCU_H__
#define __CUST_CWMCU_H__

/* GPIO for MCU control */
#define GPIO_CW_MCU_WAKE_UP		GPIO_SENSORHUB_WAKE_UP
#define GPIO_CW_MCU_BOOT		GPIO_SENSORHUB_HOST_BOOT_ROM
#define GPIO_CW_MCU_RESET		GPIO_SENSORHUB_HOST_RESET
#define GPIO_CW_MCU_INTERRUPT	GPIO_SENSORHUB_EINT_PIN


#define CWMCU_I2C_INTERFACE
//#define CWMCU_SPI_INTERFACE

#ifdef CWMCU_I2C_INTERFACE
#define CWMCU_I2C_NUMBER	1
#define GTP_DMA_MAX_TRANSACTION_LENGTH  255
#define GTP_DMA_MAX_I2C_TRANSFER_SIZE (255-1)
#define I2C_MASTER_CLOCK              100
#endif

#ifdef CWMCU_SPI_INTERFACE
#define CWMCU_SPI_INTERFACE_MAX_PKT_LENGTH_PER_TIMES (0x400)
#define CWMCU_SPI_INTERFACE_MAX_PKT_COUNT_PER_TIMES  (0x100)
#define CWMCU_SPI_CHECKSUM_SUPPORT						1
#endif

/* HW info*/
#define ACCEL_HW_INFO   {BMI160, 0x30, 20, 7, 6, {2, 4, 1, 0x0B}}
#define GYRO_HW_INFO    {BMI160, 0xD0, 20, 8, 6, {0, 0, 0, 0x00}}

/* PS threadhold*/
#define PS_HIGH_THRESHOLD		0x32
#define PS_LOW_THRESHOLD		0x2E
#endif
