/*
* Copyright (C) 2011-2014 MediaTek Inc.
*
* This program is free software: you can redistribute it and/or modify it under the terms of the
* GNU General Public License version 2 as published by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
* without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
* See the GNU General Public License for more details.
*
* You should have received a copy of the GNU General Public License along with this program.
* If not, see <http://www.gnu.org/licenses/>.
*/

#ifndef __CUST_GPIO_USAGE_H__
#define __CUST_GPIO_USAGE_H__


#define GPIO_AUD_CLK_MOSI_PIN         GPIO4
#define GPIO_AUD_CLK_MOSI_PIN_M_GPIO   GPIO_MODE_00
#define GPIO_AUD_CLK_MOSI_PIN_M_CLK   GPIO_MODE_01
#define GPIO_AUD_CLK_MOSI_PIN_M_AUD_ADC_CK   GPIO_MODE_03
#define GPIO_AUD_CLK_MOSI_PIN_M_CONN_MCU_DBGI_N   GPIO_MODE_07

#define GPIO_AUD_DAT_MISO_PIN         GPIO5
#define GPIO_AUD_DAT_MISO_PIN_M_GPIO   GPIO_MODE_00
#define GPIO_AUD_DAT_MISO_PIN_M_AUD_MISO   GPIO_MODE_01
#define GPIO_AUD_DAT_MISO_PIN_M_AUD_ADC_DAT_IN   GPIO_MODE_03
#define GPIO_AUD_DAT_MISO_PIN_M_CONN_MCU_DBGACK_N   GPIO_MODE_07

#define GPIO_AUD_DAT_MOSI_PIN         GPIO6
#define GPIO_AUD_DAT_MOSI_PIN_M_GPIO   GPIO_MODE_00
#define GPIO_AUD_DAT_MOSI_PIN_M_AUD_MOSI   GPIO_MODE_01
#define GPIO_AUD_DAT_MOSI_PIN_M_AUD_ADC_WS   GPIO_MODE_03
#define GPIO_AUD_DAT_MOSI_PIN_M_CONN_MCU_TDO   GPIO_MODE_07

#define GPIO_LCD_IO_0_PIN         GPIO14
#define GPIO_LCD_IO_0_PIN_M_GPIO   GPIO_MODE_00
#define GPIO_LCD_IO_0_PIN_M_PWM   GPIO_MODE_02
#define GPIO_LCD_IO_0_PIN_M_LPD   GPIO_MODE_01

#define GPIO_LCD_IO_1_PIN         GPIO15
#define GPIO_LCD_IO_1_PIN_M_GPIO   GPIO_MODE_00
#define GPIO_LCD_IO_1_PIN_M_PWM   GPIO_MODE_02
#define GPIO_LCD_IO_1_PIN_M_LPD   GPIO_MODE_01

#define GPIO_LCD_IO_2_PIN         GPIO16
#define GPIO_LCD_IO_2_PIN_M_GPIO   GPIO_MODE_00
#define GPIO_LCD_IO_2_PIN_M_PWM   GPIO_MODE_02
#define GPIO_LCD_IO_2_PIN_M_LPD   GPIO_MODE_01

#define GPIO_LCD_IO_3_PIN         GPIO17
#define GPIO_LCD_IO_3_PIN_M_GPIO   GPIO_MODE_00
#define GPIO_LCD_IO_3_PIN_M_LPD   GPIO_MODE_01

#define GPIO_LCD_IO_4_PIN         GPIO18
#define GPIO_LCD_IO_4_PIN_M_GPIO   GPIO_MODE_00
#define GPIO_LCD_IO_4_PIN_M_LPD   GPIO_MODE_01

#define GPIO_LCD_IO_5_PIN         GPIO19
#define GPIO_LCD_IO_5_PIN_M_GPIO   GPIO_MODE_00
#define GPIO_LCD_IO_5_PIN_M_LPD   GPIO_MODE_01

#define GPIO_LCD_IO_6_PIN         GPIO20
#define GPIO_LCD_IO_6_PIN_M_GPIO   GPIO_MODE_00
#define GPIO_LCD_IO_6_PIN_M_LPD   GPIO_MODE_01

#define GPIO_LCD_IO_7_PIN         GPIO21
#define GPIO_LCD_IO_7_PIN_M_GPIO   GPIO_MODE_00
#define GPIO_LCD_IO_7_PIN_M_KCOL   GPIO_MODE_03
#define GPIO_LCD_IO_7_PIN_M_LPD   GPIO_MODE_01

#define GPIO_PWM_BL_PIN         GPIO22
#define GPIO_PWM_BL_PIN_M_GPIO   GPIO_MODE_00
#define GPIO_PWM_BL_PIN_M_PWM   GPIO_MODE_02

#define GPIO_SENSORHUB_EINT_PIN         GPIO25
#define GPIO_SENSORHUB_EINT_PIN_M_GPIO   GPIO_MODE_00
#define GPIO_SENSORHUB_EINT_PIN_M_EINT   GPIO_MODE_02
#define GPIO_SENSORHUB_EINT_PIN_M_LPD   GPIO_MODE_01
#define GPIO_SENSORHUB_EINT_PIN_M_DPI_G   GPIO_MODE_04
#define GPIO_SENSORHUB_EINT_PIN_M_DBG_OUT   GPIO_MODE_06
#define GPIO_SENSORHUB_EINT_PIN_M_CONN_GPIO   GPIO_MODE_07

#define GPIO_SENSORHUB_WAKE_UP         GPIO26
#define GPIO_SENSORHUB_WAKE_UP_M_GPIO   GPIO_MODE_00
#define GPIO_SENSORHUB_WAKE_UP_M_EINT   GPIO_MODE_02
#define GPIO_SENSORHUB_WAKE_UP_M_LPD   GPIO_MODE_01
#define GPIO_SENSORHUB_WAKE_UP_M_DPI_R   GPIO_MODE_04
#define GPIO_SENSORHUB_WAKE_UP_M_MD_EINT   GPIO_MODE_05
#define GPIO_SENSORHUB_WAKE_UP_M_DBG_OUT   GPIO_MODE_06
#define GPIO_SENSORHUB_WAKE_UP_M_CONN_GPIO   GPIO_MODE_07

#define GPIO_SPEAKER_EN_PIN         GPIO30
#define GPIO_SPEAKER_EN_PIN_M_GPIO   GPIO_MODE_00
#define GPIO_SPEAKER_EN_PIN_M_EINT   GPIO_MODE_02
#define GPIO_SPEAKER_EN_PIN_M_PWM   GPIO_MODE_03
#define GPIO_SPEAKER_EN_PIN_M_LPD   GPIO_MODE_01
#define GPIO_SPEAKER_EN_PIN_M_DPI_R   GPIO_MODE_04
#define GPIO_SPEAKER_EN_PIN_M_CONN_MCU_AICE_TCKC   GPIO_MODE_07

#define GPIO_DISP_LRSTB_PIN         GPIO59
#define GPIO_DISP_LRSTB_PIN_M_GPIO   GPIO_MODE_00
#define GPIO_DISP_LRSTB_PIN_M_LRSTB   GPIO_MODE_02

#define GPIO_WIFI_EINT_PIN         GPIO64
#define GPIO_WIFI_EINT_PIN_M_GPIO   GPIO_MODE_00
#define GPIO_WIFI_EINT_PIN_M_EINT   GPIO_MODE_03
#define GPIO_WIFI_EINT_PIN_M_CMDAT   GPIO_MODE_01
#define GPIO_WIFI_EINT_PIN_M_MD_DSPJTD   GPIO_MODE_05
#define GPIO_WIFI_EINT_PIN_M_DBG_OUT   GPIO_MODE_06
#define GPIO_WIFI_EINT_PIN_M_CONN_GPIO   GPIO_MODE_07

#define GPIO_COMBO_PMU_EN_PIN         GPIO65
#define GPIO_COMBO_PMU_EN_PIN_M_GPIO   GPIO_MODE_00
#define GPIO_COMBO_PMU_EN_PIN_M_EINT   GPIO_MODE_03
#define GPIO_COMBO_PMU_EN_PIN_M_CMDAT   GPIO_MODE_01
#define GPIO_COMBO_PMU_EN_PIN_M_MD_DSPJTCK   GPIO_MODE_05
#define GPIO_COMBO_PMU_EN_PIN_M_DBG_OUT   GPIO_MODE_06
#define GPIO_COMBO_PMU_EN_PIN_M_CONN_GPIO   GPIO_MODE_07

#define GPIO_COMBO_RST_PIN         GPIO66
#define GPIO_COMBO_RST_PIN_M_GPIO   GPIO_MODE_00
#define GPIO_COMBO_RST_PIN_M_EINT   GPIO_MODE_03
#define GPIO_COMBO_RST_PIN_M_CMDAT   GPIO_MODE_01
#define GPIO_COMBO_RST_PIN_M_MD_DSPJTMS   GPIO_MODE_05
#define GPIO_COMBO_RST_PIN_M_DBG_OUT   GPIO_MODE_06
#define GPIO_COMBO_RST_PIN_M_CONN_GPIO   GPIO_MODE_07

#define GPIO_CAMERA_CMRST_PIN         GPIO87
#define GPIO_CAMERA_CMRST_PIN_M_GPIO   GPIO_MODE_00
#define GPIO_CAMERA_CMRST_PIN_M_EINT   GPIO_MODE_01
#define GPIO_CAMERA_CMRST_PIN_M_KCOL   GPIO_MODE_03
#define GPIO_CAMERA_CMRST_PIN_M_SFCS   GPIO_MODE_02
#define GPIO_CAMERA_CMRST_PIN_M_TDD_TXD   GPIO_MODE_04
#define GPIO_CAMERA_CMRST_PIN_M_JTCK   GPIO_MODE_05
#define GPIO_CAMERA_CMRST_PIN_M_DBG_OUT   GPIO_MODE_06
#define GPIO_CAMERA_CMRST_PIN_M_CONN_GPIO   GPIO_MODE_07

#define GPIO_CAMERA_CMPDN_PIN         GPIO88
#define GPIO_CAMERA_CMPDN_PIN_M_GPIO   GPIO_MODE_00
#define GPIO_CAMERA_CMPDN_PIN_M_EINT   GPIO_MODE_01
#define GPIO_CAMERA_CMPDN_PIN_M_KCOL   GPIO_MODE_03
#define GPIO_CAMERA_CMPDN_PIN_M_MC1_INS   GPIO_MODE_02
#define GPIO_CAMERA_CMPDN_PIN_M_JTMS   GPIO_MODE_05
#define GPIO_CAMERA_CMPDN_PIN_M_DBG_OUT   GPIO_MODE_06
#define GPIO_CAMERA_CMPDN_PIN_M_CONN_GPIO   GPIO_MODE_07

#define GPIO_GPS_LNA_PIN         GPIO90
#define GPIO_GPS_LNA_PIN_M_GPIO   GPIO_MODE_00
#define GPIO_GPS_LNA_PIN_M_EINT   GPIO_MODE_01
#define GPIO_GPS_LNA_PIN_M_KCOL   GPIO_MODE_03
#define GPIO_GPS_LNA_PIN_M_SDA   GPIO_MODE_02
#define GPIO_GPS_LNA_PIN_M_SIM2_SRST   GPIO_MODE_04
#define GPIO_GPS_LNA_PIN_M_JTDO   GPIO_MODE_05
#define GPIO_GPS_LNA_PIN_M_DBG_OUT   GPIO_MODE_06
#define GPIO_GPS_LNA_PIN_M_CONN_GPIO   GPIO_MODE_07

#define GPIO_MSDC1_CLK         GPIO91
#define GPIO_MSDC1_CLK_M_GPIO   GPIO_MODE_00
#define GPIO_MSDC1_CLK_M_MC1_CK   GPIO_MODE_01

#define GPIO_MSDC0_CMD         GPIO92
#define GPIO_MSDC0_CMD_M_GPIO   GPIO_MODE_00
#define GPIO_MSDC0_CMD_M_MC1_CMD   GPIO_MODE_01

#define GPIO_MSDC1_DAT0         GPIO93
#define GPIO_MSDC1_DAT0_M_GPIO   GPIO_MODE_00
#define GPIO_MSDC1_DAT0_M_MC1_DAT   GPIO_MODE_01

#define GPIO_MSDC1_DAT1         GPIO94
#define GPIO_MSDC1_DAT1_M_GPIO   GPIO_MODE_00
#define GPIO_MSDC1_DAT1_M_MC1_DAT   GPIO_MODE_01

#define GPIO_MSDC1_DAT2         GPIO95
#define GPIO_MSDC1_DAT2_M_GPIO   GPIO_MODE_00
#define GPIO_MSDC1_DAT2_M_MC1_DAT   GPIO_MODE_01

#define GPIO_MSDC1_DAT3         GPIO96
#define GPIO_MSDC1_DAT3_M_GPIO   GPIO_MODE_00
#define GPIO_MSDC1_DAT3_M_MC1_DAT   GPIO_MODE_01

#define GPIO_SPI_MISO_PIN         GPIO100
#define GPIO_SPI_MISO_PIN_M_GPIO   GPIO_MODE_00
#define GPIO_SPI_MISO_PIN_M_CLK   GPIO_MODE_02
#define GPIO_SPI_MISO_PIN_M_EINT   GPIO_MODE_04
#define GPIO_SPI_MISO_PIN_M_KROW   GPIO_MODE_03
#define GPIO_SPI_MISO_PIN_M_SPI_MISO   GPIO_MODE_01

#define GPIO_UART_URXD2_PIN         GPIO101
#define GPIO_UART_URXD2_PIN_M_GPIO   GPIO_MODE_00
#define GPIO_UART_URXD2_PIN_M_EINT   GPIO_MODE_02
#define GPIO_UART_URXD2_PIN_M_URXD   GPIO_MODE_01

#define GPIO_COMBO_URXD_PIN         GPIO101
#define GPIO_COMBO_URXD_PIN_M_GPIO   GPIO_MODE_00
#define GPIO_COMBO_URXD_PIN_M_EINT   GPIO_MODE_02
#define GPIO_COMBO_URXD_PIN_M_URXD   GPIO_MODE_01

#define GPIO_UART_UTXD2_PIN         GPIO102
#define GPIO_UART_UTXD2_PIN_M_GPIO   GPIO_MODE_00
#define GPIO_UART_UTXD2_PIN_M_PWM   GPIO_MODE_02
#define GPIO_UART_UTXD2_PIN_M_UTXD   GPIO_MODE_01

#define GPIO_COMBO_UTXD_PIN         GPIO102
#define GPIO_COMBO_UTXD_PIN_M_GPIO   GPIO_MODE_00
#define GPIO_COMBO_UTXD_PIN_M_PWM   GPIO_MODE_02
#define GPIO_COMBO_UTXD_PIN_M_UTXD   GPIO_MODE_01

#define GPIO_UART_URXD1_PIN         GPIO103
#define GPIO_UART_URXD1_PIN_M_GPIO   GPIO_MODE_00
#define GPIO_UART_URXD1_PIN_M_URXD   GPIO_MODE_01

#define GPIO_UART_UTXD1_PIN         GPIO104
#define GPIO_UART_UTXD1_PIN_M_GPIO   GPIO_MODE_00
#define GPIO_UART_UTXD1_PIN_M_UTXD   GPIO_MODE_01

#define GPIO_I2C0_SCA_PIN         GPIO105
#define GPIO_I2C0_SCA_PIN_M_GPIO   GPIO_MODE_00
#define GPIO_I2C0_SCA_PIN_M_SCL   GPIO_MODE_01

#define GPIO_I2C0_SDA_PIN         GPIO106
#define GPIO_I2C0_SDA_PIN_M_GPIO   GPIO_MODE_00
#define GPIO_I2C0_SDA_PIN_M_SDA   GPIO_MODE_01

#define GPIO_KPD_KCOL0_PIN         GPIO107
#define GPIO_KPD_KCOL0_PIN_M_GPIO   GPIO_MODE_00
#define GPIO_KPD_KCOL0_PIN_M_KCOL   GPIO_MODE_01

#define GPIO_KPD_KROW0_PIN         GPIO110
#define GPIO_KPD_KROW0_PIN_M_GPIO   GPIO_MODE_00
#define GPIO_KPD_KROW0_PIN_M_KROW   GPIO_MODE_01

#define GPIO_I2C1_SCA_PIN         GPIO113
#define GPIO_I2C1_SCA_PIN_M_GPIO   GPIO_MODE_00
#define GPIO_I2C1_SCA_PIN_M_SCL   GPIO_MODE_01

#define GPIO_I2C1_SDA_PIN         GPIO114
#define GPIO_I2C1_SDA_PIN_M_GPIO   GPIO_MODE_00
#define GPIO_I2C1_SDA_PIN_M_SDA   GPIO_MODE_01

#define GPIO_I2S0_WS_PIN         GPIO134
#define GPIO_I2S0_WS_PIN_M_GPIO   GPIO_MODE_00
#define GPIO_I2S0_WS_PIN_M_PWM   GPIO_MODE_04
#define GPIO_I2S0_WS_PIN_M_I2S_OUT_WS   GPIO_MODE_05

#define GPIO_COMBO_I2S_WS_PIN         GPIO134
#define GPIO_COMBO_I2S_WS_PIN_M_GPIO   GPIO_MODE_00
#define GPIO_COMBO_I2S_WS_PIN_M_PWM   GPIO_MODE_04
#define GPIO_COMBO_I2S_WS_PIN_M_I2S_OUT_WS   GPIO_MODE_05

#define GPIO_I2S_CLK_PIN         GPIO135
#define GPIO_I2S_CLK_PIN_M_GPIO   GPIO_MODE_00
#define GPIO_I2S_CLK_PIN_M_EINT   GPIO_MODE_04
#define GPIO_I2S_CLK_PIN_M_I2S_OUT_CK   GPIO_MODE_05

#define GPIO_COMBO_I2S_CK_PIN         GPIO135
#define GPIO_COMBO_I2S_CK_PIN_M_GPIO   GPIO_MODE_00
#define GPIO_COMBO_I2S_CK_PIN_M_EINT   GPIO_MODE_04
#define GPIO_COMBO_I2S_CK_PIN_M_I2S_OUT_CK   GPIO_MODE_05

#define GPIO_I2S_DAT_OUT_PIN         GPIO136
#define GPIO_I2S_DAT_OUT_PIN_M_GPIO   GPIO_MODE_00
#define GPIO_I2S_DAT_OUT_PIN_M_EINT   GPIO_MODE_04
#define GPIO_I2S_DAT_OUT_PIN_M_I2S_OUT_DAT   GPIO_MODE_05

#define GPIO_COMBO_I2S_DAT_PIN         GPIO136
#define GPIO_COMBO_I2S_DAT_PIN_M_GPIO   GPIO_MODE_00
#define GPIO_COMBO_I2S_DAT_PIN_M_EINT   GPIO_MODE_04
#define GPIO_COMBO_I2S_DAT_PIN_M_I2S_OUT_DAT   GPIO_MODE_05

#define GPIO_CTP_EINT_PIN         GPIO129
#define GPIO_CTP_EINT_PIN_M_GPIO   GPIO_MODE_00
#define GPIO_CTP_EINT_PIN_M_CLK   GPIO_MODE_05
#define GPIO_CTP_EINT_PIN_M_EINT   GPIO_MODE_02
#define GPIO_CTP_EINT_PIN_M_PWM   GPIO_MODE_01
#define GPIO_CTP_EINT_PIN_CLK     CLK_OUT1
#define GPIO_CTP_EINT_PIN_FREQ    GPIO_CLKSRC_NONE


#define GPIO_CTP_RST_PIN         GPIO142
#define GPIO_CTP_RST_PIN_M_GPIO   GPIO_MODE_00
#define GPIO_CTP_RST_PIN_M_EINT   GPIO_MODE_03
#define GPIO_CTP_RST_PIN_M_KROW   GPIO_MODE_05
#define GPIO_CTP_RST_PIN_M_BPI_BUS   GPIO_MODE_01
#define GPIO_CTP_RST_PIN_M_LSA   GPIO_MODE_02
#define GPIO_CTP_RST_PIN_M_I2S_IN_WS   GPIO_MODE_04
#define GPIO_CTP_RST_PIN_M_DBG_OUT   GPIO_MODE_06
#define GPIO_CTP_RST_PIN_M_CONN_GPIO   GPIO_MODE_07

#define GPIO_SENSORHUB_HOST_BOOT_ROM         GPIO143
#define GPIO_SENSORHUB_HOST_BOOT_ROM_M_GPIO   GPIO_MODE_00
#define GPIO_SENSORHUB_HOST_BOOT_ROM_M_EINT   GPIO_MODE_03
#define GPIO_SENSORHUB_HOST_BOOT_ROM_M_KROW   GPIO_MODE_05
#define GPIO_SENSORHUB_HOST_BOOT_ROM_M_PWM   GPIO_MODE_02
#define GPIO_SENSORHUB_HOST_BOOT_ROM_M_BPI_BUS   GPIO_MODE_01
#define GPIO_SENSORHUB_HOST_BOOT_ROM_M_I2S_IN_DAT   GPIO_MODE_04
#define GPIO_SENSORHUB_HOST_BOOT_ROM_M_DBG_OUT   GPIO_MODE_06
#define GPIO_SENSORHUB_HOST_BOOT_ROM_M_CONN_GPIO   GPIO_MODE_07

#define GPIO_SENSORHUB_HOST_RESET         GPIO145
#define GPIO_SENSORHUB_HOST_RESET_M_GPIO   GPIO_MODE_00
#define GPIO_SENSORHUB_HOST_RESET_M_EINT   GPIO_MODE_03
#define GPIO_SENSORHUB_HOST_RESET_M_KROW   GPIO_MODE_05
#define GPIO_SENSORHUB_HOST_RESET_M_PWM   GPIO_MODE_02
#define GPIO_SENSORHUB_HOST_RESET_M_BPI_BUS   GPIO_MODE_01
#define GPIO_SENSORHUB_HOST_RESET_M_LSDI   GPIO_MODE_04
#define GPIO_SENSORHUB_HOST_RESET_M_DBG_OUT   GPIO_MODE_06
#define GPIO_SENSORHUB_HOST_RESET_M_CONN_GPIO   GPIO_MODE_07


/*Output for default variable names*/
/*@XXX_XX_PIN in gpio.cmp          */



#endif				/* __CUST_GPIO_USAGE_H__ */
